# Generated by Django 4.1.3 on 2023-05-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Academico", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Estudiante",
            fields=[
                (
                    "carnet",
                    models.CharField(max_length=7, primary_key=True, serialize=False),
                ),
                ("nombres", models.CharField(max_length=25)),
                ("apellidos", models.CharField(max_length=25)),
                ("edad", models.PositiveSmallIntegerField()),
            ],
        ),
    ]
